alias sRenameScript='cd /home/vinesma/Videos/Anime/Seasonals; bash runScript.sh; cd; notify-send "renameScript finished!"'
alias cls='clear && ls'
alias mpvd='mpv --profile=youtube720p'
alias mpvl='mpv --profile=youtube360p'
alias mpvw='mpv --profile=window'
alias mpva='mpv --profile=audio-only'
alias mpvsw='mpv --profile=window-stream'
alias youtube-dl-audio='youtube-dl -x --audio-format mp3'
alias sd='shutdown now'
alias ip='ip -br -c'
alias updateAliases='. ~/.bashrc'
