#!/bin/bash
udiskie &
. ~/.config/polybar/launch.sh &
feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" &
picom &
redshift &
fcitx &
syncthing --no-browser &
xinput set-prop 12 301 1

if [[ ! -s ~/.config/mpd/pid ]]; then
    mpd
    mpc random on
    mpc repeat on
    mpc crossfade 3
fi

if nm-online; then
    firefox &
    qbittorrent &
    sleep 10 && bash ~/.dotfiles/scripts/newsboat/newsboat-reloader.sh &
fi
