#!/bin/bash
# USE chmod +x $FILE to make this file an executable

#. ~/.dotfiles/polybar/launch.sh &
thunar --daemon &
dunst &
feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" &
picom --experimental-backends &
redshift-gtk &
fcitx &
syncthing --no-browser &

# mpd startup
if [[ ! -s ~/.config/mpd/pid ]]; then
    mpd
    mpc random on
    mpc repeat on
    mpc crossfade 3
fi

# Check connection, then run network based apps.
if ping -c 2 archlinux.org; then
    firefox about:newtab https://en.wikipedia.org/wiki/Main_Page &
    sleep 15 && bash ~/.dotfiles/scripts/newsboat/newsboat-reloader.sh &
fi

# Fetch mail if conditions apply.
if [[ $(( $(date +%M) % 10 )) -le 6 ]]; then
    sleep 10 && bash ~/.dotfiles/scripts/cron-jobs/email/fetch-mail.sh &
fi
