#!/bin/bash
#. $HOME/.dotfiles/polybar/launch.sh &
thunar --daemon &
dunst &
numlockx &
redshift-gtk &
fcitx &
feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" &
picom --experimental-backends &
syncthing --no-browser &

if [[ ! -s ~/.config/mpd/pid ]]; then
    mpd
    mpc random on
    mpc repeat on
    mpc crossfade 3
fi

firefox about:newtab https://en.wikipedia.org/wiki/Main_Page &
qbittorrent --no-splash &
sleep 20 && bash ~/.dotfiles/scripts/newsboat/newsboat-reloader.sh &
