#!/bin/bash
# USE chmod +x $FILE to make this file an executable

udiskie &
. ~/.dotfiles/polybar/launch.sh &
feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" &
picom --experimental-backends &
redshift-gtk &
fcitx &
syncthing --no-browser &
xinput set-prop 12 301 1

# mpd startup
if [[ ! -s ~/.config/mpd/pid ]]; then
    mpd
    mpc random on
    mpc repeat on
    mpc crossfade 3
fi

# Check connection, then run network based apps.
if ping -c 2 google.com; then
    firefox about:newtab https://en.wikipedia.org/wiki/Main_Page &
    sleep 15 && bash ~/.dotfiles/scripts/newsboat/newsboat-reloader.sh &
fi

# Remove empty video directories.
rmdir --ignore-fail-on-non-empty ~/Videos/Others/*
rmdir --ignore-fail-on-non-empty ~/Videos/Streams/*

# Fetch mail if conditions apply.
if [[ $(( $(date +%M) % 10 )) -le 6 ]]; then
    sleep 10 && bash ~/.dotfiles/scripts/cron-jobs/email/fetch-mail.sh &
fi
