#!/bin/bash
# USE chmod +x $FILE to make this file an executable

udiskie &
. ~/.dotfiles/polybar/launch.sh &
feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" &
picom --experimental-backends &
redshift-gtk &
fcitx &
syncthing --no-browser &
xinput set-prop 12 301 1

if [[ ! -s ~/.config/mpd/pid ]]; then
    mpd
    mpc random on
    mpc repeat on
    mpc crossfade 3
fi

if ping -c 2 google.com; then
    firefox about:newtab https://en.wikipedia.org/wiki/Main_Page &
    sleep 15 && bash ~/.dotfiles/scripts/newsboat/newsboat-reloader.sh &
fi

rmdir --ignore-fail-on-non-empty ~/Videos/Others/*
rmdir --ignore-fail-on-non-empty ~/Videos/Streams/*
